# Generated by Django 5.2.13 on 2026-05-05 02:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('asunto', models.CharField(blank=True, max_length=150, null=True)),
                ('mensaje', models.TextField()),
                ('ip_origen', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contactos',
                'indexes': [models.Index(fields=['correo'], name='contactos_correo_ecba4d_idx'), models.Index(fields=['fecha_envio'], name='contactos_fecha_e_dbb468_idx'), models.Index(fields=['leido'], name='contactos_leido_d14884_idx')],
            },
        ),
    ]
