# Generated by Django 6.0.6 on 2026-06-30 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_alter_contacto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='asunto',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Asunto'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='correo',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='fecha_lectura',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID del mensaje'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='ip_origen',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Dirección IP de origen'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='leido',
            field=models.BooleanField(default=False, verbose_name='¿Leído?'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='mensaje',
            field=models.TextField(verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre completo'),
        ),
    ]
