services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: proyecto_backend
    command: ["gunicorn", "config.wsgi:application", "--bind", "0.0.0.0:8000", "--reload"]
    volumes:
      - ./backend:/app
      - backend_media:/app/media
      - backend_static:/app/static
    ports:
      - '8000:8000'
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: proyecto_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '5173:5173'
    env_file:
      - .env
    environment:
      - VITE_API_URL=/api/
    depends_on:
      - backend

  tshirt3d:
    build:
      context: ./microservices/Tshirt3D
      dockerfile: Dockerfile
    container_name: proyecto_tshirt3d
    working_dir: /app
    volumes:
      - ./microservices/Tshirt3D:/app
      - /app/node_modules
    ports:
      - '5174:5174'
    env_file:
      - .env
    depends_on:
      - backend

volumes:
  backend_media:
  backend_static:
