# Generated by Django 5.2.13 on 2026-05-05 02:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=100, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('contrasena', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Bloqueado', 'Bloqueado')], default='Inactivo', max_length=20)),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Usuario', 'Usuario')], default='Usuario', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_sesion', models.DateTimeField(blank=True, null=True)),
                ('email_verificado', models.BooleanField(default=False)),
                ('intentos_fallidos', models.IntegerField(default=0)),
                ('fecha_bloqueo', models.DateTimeField(blank=True, null=True)),
                ('fecha_desbloqueo', models.DateTimeField(blank=True, null=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('admin_desbloqueador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_desbloqueados', to='users.usuario')),
                ('admin_eliminador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_eliminados', to='users.usuario')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Token_Verificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('tipo', models.CharField(choices=[('Verificacion_Email', 'Verificación de Email'), ('Recuperacion_Password', 'Recuperación de Contraseña'), ('Cambio_Email', 'Cambio de Email')], max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_verificacion', to='users.usuario')),
            ],
            options={
                'db_table': 'tokens_verificacion',
            },
        ),
        migrations.CreateModel(
            name='Log_Auditoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=255)),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('ip_admin', models.CharField(blank=True, max_length=45, null=True)),
                ('usuario_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_realizadas', to='users.usuario')),
                ('usuario_afectado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_recibidas', to='users.usuario')),
            ],
            options={
                'db_table': 'logs_auditoria',
            },
        ),
        migrations.CreateModel(
            name='Historial_Estado_Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_anterior', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Bloqueado', 'Bloqueado')], max_length=20)),
                ('estado_nuevo', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Bloqueado', 'Bloqueado')], max_length=20)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_estado_realizados', to='users.usuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='users.usuario')),
            ],
            options={
                'db_table': 'historial_estado_usuarios',
            },
        ),
        migrations.CreateModel(
            name='Cambio_Email',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email_anterior', models.EmailField(max_length=254)),
                ('email_nuevo', models.EmailField(max_length=254)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('verificado', models.BooleanField(default=False)),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.token_verificacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_email', to='users.usuario')),
            ],
            options={
                'db_table': 'cambios_email',
            },
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['usuario'], name='usuarios_usuario_cce775_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['correo'], name='usuarios_correo_ee1198_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['estado', 'rol'], name='usuarios_estado_6d06ec_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['fecha_registro'], name='usuarios_fecha_r_b3e269_idx'),
        ),
        migrations.AddIndex(
            model_name='token_verificacion',
            index=models.Index(fields=['token'], name='tokens_veri_token_1aa296_idx'),
        ),
        migrations.AddIndex(
            model_name='token_verificacion',
            index=models.Index(fields=['usuario', 'tipo'], name='tokens_veri_usuario_07d168_idx'),
        ),
        migrations.AddIndex(
            model_name='token_verificacion',
            index=models.Index(fields=['fecha_expiracion'], name='tokens_veri_fecha_e_4f6f92_idx'),
        ),
        migrations.AddIndex(
            model_name='log_auditoria',
            index=models.Index(fields=['usuario_admin', 'fecha_accion'], name='logs_audito_usuario_5ea853_idx'),
        ),
        migrations.AddIndex(
            model_name='log_auditoria',
            index=models.Index(fields=['usuario_afectado', 'fecha_accion'], name='logs_audito_usuario_ae9c2b_idx'),
        ),
        migrations.AddIndex(
            model_name='log_auditoria',
            index=models.Index(fields=['fecha_accion'], name='logs_audito_fecha_a_a6979c_idx'),
        ),
        migrations.AddIndex(
            model_name='historial_estado_usuario',
            index=models.Index(fields=['usuario', 'fecha_cambio'], name='historial_e_usuario_773c03_idx'),
        ),
        migrations.AddIndex(
            model_name='cambio_email',
            index=models.Index(fields=['usuario', 'verificado'], name='cambios_ema_usuario_1bf888_idx'),
        ),
    ]
