# Generated by Django 5.2.13 on 2026-06-09 18:36

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token_verificacion',
            name='token',
            field=models.CharField(default=secrets.token_urlsafe, max_length=255, unique=True),
        ),
    ]
