# Generated by Django 5.2.13 on 2026-09-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_token_verificacion_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token_verificacion',
            name='tipo',
            field=models.CharField(choices=[('Verificacion_Email', 'Verificación de Email'), ('Recuperacion_Password', 'Recuperación de Contraseña')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Cambio_Email',
        ),
    ]
