# Generated by Django 6.0.6 on 2026-06-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usuario_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='token_version',
            field=models.IntegerField(default=0, verbose_name='Versión de token'),
        ),
    ]
