# Generated by Django 6.0.6 on 2026-09-06 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_is_staff_is_superuser_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='usuario',
            name='token_version',
            field=models.IntegerField(default=0, verbose_name='Versión de token'),
        ),
        migrations.AlterField(
            model_name='token_verificacion',
            name='tipo',
            field=models.CharField(choices=[('Verificacion_Email', 'Verificación de Email'), ('Recuperacion_Password', 'Recuperación de Contraseña'), ('Cambio_Email', 'Cambio de Email')], max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Superusuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=100, unique=True, verbose_name='username'),
        ),
        migrations.CreateModel(
            name='Cambio_Email',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email_anterior', models.EmailField(max_length=254)),
                ('email_nuevo', models.EmailField(max_length=254)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('verificado', models.BooleanField(default=False)),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.token_verificacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_email', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cambios_email',
                'indexes': [models.Index(fields=['usuario', 'verificado'], name='cambios_ema_usuario_1bf888_idx')],
            },
        ),
    ]
