# Generated by Django 5.2.13 on 2026-09-07 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_usuario_is_staff_usuario_token_version_and_more'),
        ('users', '0005_usuario_token_version'),
    ]

    operations = [
    ]
