# Generated by Django 5.2.13 on 2026-09-04 19:34
# Merge recuperacion-estable: elimina el modelo Cambio_Email (ya removido
# del codigo/models.py) y redefine TIPO_CHOICES de token_verificacion.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usuario_token_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token_verificacion',
            name='tipo',
            field=models.CharField(choices=[('Verificacion_Email', 'Verificación de Email'), ('Recuperacion_Password', 'Recuperación de Contraseña')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Cambio_Email',
        ),
    ]