# Generated by Django 5.2.13 on 2026-09-07 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_alter_cart_session_key'),
        ('carts', '0004_alter_cart_session_key'),
    ]

    operations = [
    ]
