# Generated by Django 5.2.13 on 2026-09-07 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_merge_20260907_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order',
        ),
    ]
