# Generated by Django 5.2.13 on 2026-09-10 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_remove_cart_order'),
        ('products', '0006_remove_productimage_cloudinary_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='products.productimage'),
        ),
    ]
