# Generated by Django 5.2.13 on 2026-09-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_remove_cart_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='design_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='design_preview_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
