# Generated by Django 5.2.13 on 2026-09-10 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_add_product_image_to_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='design_url',
            field=models.URLField(blank=True, help_text='URL privada del diseño del usuario (Cloudinary). No se muestra en el catálogo.', max_length=500, null=True),
        ),
    ]
