# Generated by Django 5.2.13 on 2026-09-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_cartitem_design_data_cartitem_design_preview_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_ref',
            field=models.CharField(blank=True, db_index=True, max_length=24, null=True),
        ),
    ]
