# Generated by Django 5.2.13 on 2026-09-29 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_cartitem_product_ref'),
        ('products', '0012_alter_review_product_review_review_tiene_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant_ref',
            field=models.CharField(blank=True, db_index=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.variant'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product_ref', 'variant_ref'), name='unique_cart_productref_variantref'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(('product__isnull', False), ('product_ref__isnull', False), _connector='OR'), name='cartitem_tiene_producto'),
        ),
    ]
