# Generated by Django 6.1 on 2026-08-09 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_cloudinary_public_id_order_design_color_and_more'),
        ('users', '0002_alter_token_verificacion_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.usuario'),
        ),
    ]
