# Generated by Django 6.0.6 on 2026-09-06 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_user'),
    ]

    # This branch duplicated fields already created by 0004_add_shipping_payment_fields.
    operations = []
