# Generated by Django 5.2.13 on 2026-06-23 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_add_shipping_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='design_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='full_texture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.TextField(blank=True, help_text='Imagen capturada del pedido en Base64', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL segura de Cloudinary', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='logo_scale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='logo_texture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
