# Generated by Django 5.2.13 on 2026-09-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_order_number_order_payment_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se entregó el pedido', null=True),
        ),
    ]
