# Generated by Django 5.2.13 on 2026-09-07 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_delivered_at'),
        ('orders', '0007_invoice'),
    ]

    operations = [
    ]
