# Generated by Django 5.2.13 on 2026-09-11 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_merge_0005_order_delivered_at_0007_invoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_approved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp cuando admin aprobó el diseño', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='admin_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pendiente_validacion', 'Pendiente de Validación'), ('aprobado', 'Aprobado'), ('pendiente_pago', 'Pendiente de Pago'), ('pagado', 'Pagado'), ('produccion', 'Producción'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente_validacion', max_length=30),
        ),
    ]
