# Generated by Django 5.2.13 on 2026-09-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orderitem_product_name_orderitem_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_ref',
            field=models.CharField(blank=True, db_index=True, max_length=24, null=True),
        ),
    ]
