# Generated by Django 6.0.6 on 2026-09-06 00:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogfilter',
            name='config',
            field=models.JSONField(default=dict, help_text='Configuración del filtro en JSON'),
        ),
        migrations.AlterField(
            model_name='catalogfilter',
            name='filter_type',
            field=models.CharField(choices=[('price_range', 'Rango de precio'), ('size', 'Talla'), ('color', 'Color'), ('category', 'Categoría'), ('availability', 'Disponibilidad')], max_length=20),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='filters',
            field=models.JSONField(default=dict, help_text='Filtros aplicados en la búsqueda (formato JSON)'),
        ),
    ]
