# Generated by Django 5.2.13 on 2026-09-07 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_catalogfilter_config_and_more'),
        ('catalog', '0003_alter_catalogfilter_config_and_more'),
    ]

    operations = [
    ]
