# Generated by Django 5.2.13 on 2026-09-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_merge_20260907_1735'),
        ('products', '0011_review_product_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='product_ref',
            field=models.CharField(blank=True, db_index=True, max_length=24, null=True),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('product_ref', 'category'), name='unique_productref_category'),
        ),
    ]
