# Generated by Django 5.2.13 on 2026-09-29 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productcategory_product_ref_and_more'),
        ('products', '0012_alter_review_product_review_review_tiene_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.product'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.CheckConstraint(condition=models.Q(('product__isnull', False), ('product_ref__isnull', False), _connector='OR'), name='productcategory_tiene_producto'),
        ),
    ]
