# Generated by Django 5.2.13 on 2026-06-03 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre del modelo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('cloudinary_url', models.URLField(help_text='URL segura del modelo almacenado en Cloudinary', max_length=500, verbose_name='URL Cloudinary')),
                ('cloudinary_public_id', models.CharField(blank=True, help_text='ID público del archivo en Cloudinary', max_length=255, null=True, verbose_name='Public ID Cloudinary')),
                ('file_type', models.CharField(choices=[('glb', 'GLB'), ('gltf', 'GLTF'), ('obj', 'OBJ'), ('fbx', 'FBX'), ('dae', 'DAE')], default='glb', max_length=20, verbose_name='Tipo de archivo')),
                ('file_size', models.BigIntegerField(blank=True, help_text='Tamaño en bytes del archivo almacenado', null=True, verbose_name='Tamaño del archivo (bytes)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Modelo 3D',
                'verbose_name_plural': 'Modelos 3D',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Model3DImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloudinary_url', models.URLField(help_text='URL segura de la imagen de preview en Cloudinary', max_length=500, verbose_name='URL Cloudinary')),
                ('cloudinary_public_id', models.CharField(blank=True, help_text='ID público del archivo en Cloudinary', max_length=255, null=True, verbose_name='Public ID Cloudinary')),
                ('is_main', models.BooleanField(default=False, verbose_name='Es imagen principal')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('model_3d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_images', to='models3d.model3d', verbose_name='Modelo 3D')),
            ],
            options={
                'verbose_name': 'Imagen del modelo 3D',
                'verbose_name_plural': 'Imágenes del modelo 3D',
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('model_3d', 'order'), name='unique_model3d_image_order')],
            },
        ),
    ]
