# Generated by Django 5.2.13 on 2026-08-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models3d', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudinaryResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Recurso Cloudinary',
                'verbose_name_plural': 'Gestor Cloudinary',
                'managed': False,
            },
        ),
    ]
