# Generated by Django 5.2.13 on 2026-09-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models3d', '0002_cloudinaryresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model3d',
            name='file_type',
            field=models.CharField(choices=[('png', 'PNG'), ('jpg', 'JPG'), ('jpeg', 'JPEG'), ('webp', 'WEBP'), ('glb', 'GLB'), ('gltf', 'GLTF'), ('obj', 'OBJ'), ('fbx', 'FBX'), ('dae', 'DAE')], default='glb', max_length=20, verbose_name='Tipo de archivo'),
        ),
    ]
