# Generated by Django 5.2.13 on 2026-09-08 11:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models3d', '0003_alter_model3d_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Sesión del Editor 3D',
                'verbose_name_plural': 'Sesiones del Editor 3D',
            },
        ),
    ]
