# Generated by Django 5.2.13 on 2026-09-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models3d', '0004_editorsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorsession',
            name='is_admin_session',
            field=models.BooleanField(default=False),
        ),
    ]
