# Generated by Django 5.2.13 on 2026-08-04 19:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0002_alter_token_verificacion_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_approved', to='users.usuario'),
        ),
        migrations.AddField(
            model_name='product',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_created', to='users.usuario'),
        ),
        migrations.AddField(
            model_name='productaudit',
            name='motivo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='variant',
            name='color_hex',
            field=models.CharField(blank=True, default='#6B7280', max_length=7),
        ),
        migrations.AddField(
            model_name='variant',
            name='color_nombre',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='variant',
            name='price_variant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='productaudit',
            name='action',
            field=models.CharField(choices=[('created', 'Creado'), ('updated', 'Actualizado'), ('published', 'Publicado'), ('disapproved', 'Desaprobado')], max_length=20),
        ),
    ]
