# Generated by Django 5.2.13 on 2026-09-07 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_backfill_colors_and_cop_prices'),
        ('products', '0004_review'),
    ]

    operations = [
    ]
