# Generated by Django 5.2.13 on 2026-09-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_merge_0003_backfill_colors_and_cop_prices_0004_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='cloudinary_url',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='precio_variante',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/%Y/%m'),
        ),
        migrations.DeleteModel(
            name='MotivoDesaprobacion',
        ),
    ]
