# Generated by Django 5.2.13 on 2026-09-22 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_productimage_cloudinary_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='referencia',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
