# Generated by Django 5.2.13 on 2026-09-24 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_add_referencia_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productaudit',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='products.product'),
        ),
    ]
