# Generated by Django 5.2.13 on 2026-09-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productaudit_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productaudit',
            name='action',
            field=models.CharField(choices=[('created', 'Creado'), ('updated', 'Actualizado'), ('published', 'Publicado'), ('disapproved', 'Desaprobado'), ('deleted', 'Soft delete')], max_length=20),
        ),
    ]
