# Generated by Django 5.2.13 on 2026-09-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_productaudit_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='version',
            field=models.BigIntegerField(default=0, help_text='Optimistic locking. Lo incrementa Spring Boot (@Version) y Django.'),
        ),
    ]
