# Generated by Django 5.2.13 on 2026-09-29 00:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_add_version_column'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product_ref',
            field=models.CharField(blank=True, db_index=True, max_length=24, null=True),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('product_ref', 'user'), name='unique_productref_user_review'),
        ),
    ]
